-- =============================================================
-- Seed: Default Practitioner curriculum template (Week 0-10)
-- created_by is NULL here — Super Admin is linked after manual setup
-- =============================================================
do $$
declare
  v_template_id uuid;
begin
  insert into public.curriculum_templates (name, level, platform, is_default, created_by)
  values ('AWS re/Start Standard (Practitioner)', 'practitioner', 'canvas', true, null)
  on conflict do nothing
  returning id into v_template_id;

  if v_template_id is null then return; end if;

  insert into public.template_tasks (template_id, week_number, task_name, task_type, display_order) values
    -- Week 1 KCs
    (v_template_id, 1, 'KC - Introduction to Cloud Computing', 'kc', 1),
    (v_template_id, 1, 'KC - Basic Computing Concepts', 'kc', 2),
    (v_template_id, 1, 'KC - Development Team Roles', 'kc', 3),
    (v_template_id, 1, 'KC - What is Cloud Computing?', 'kc', 4),
    (v_template_id, 1, 'KC - Advantages of Cloud Computing', 'kc', 5),
    (v_template_id, 1, 'KC - What is Amazon Web Services?', 'kc', 6),
    (v_template_id, 1, 'KC - Fundamentals of AWS Pricing', 'kc', 7),
    (v_template_id, 1, 'KC - AWS Infrastructure Overview', 'kc', 8),
    (v_template_id, 1, 'KC - AWS Services and Service Categories', 'kc', 9),
    (v_template_id, 1, 'KC - Shared Responsibility Model', 'kc', 10),
    (v_template_id, 1, 'KC - Introduction to Amazon S3', 'kc', 11),
    -- Week 1 Lab
    (v_template_id, 1, '1-[CF]-Lab - Sandbox Environment', 'lab', 1),
    -- Week 2 KCs
    (v_template_id, 2, 'KC - Introduction to Amazon EC2', 'kc', 1),
    (v_template_id, 2, 'KC - An Introduction to Linux', 'kc', 2),
    (v_template_id, 2, 'KC - Linux Command Line', 'kc', 3),
    (v_template_id, 2, 'KC - Users and Groups', 'kc', 4),
    (v_template_id, 2, 'KC - Editing Files', 'kc', 5),
    (v_template_id, 2, 'KC - Working with the File System', 'kc', 6),
    (v_template_id, 2, 'KC - Working with Files', 'kc', 7),
    (v_template_id, 2, 'KC - Managing File Permissions', 'kc', 8),
    (v_template_id, 2, 'KC - Working with Commands', 'kc', 9),
    (v_template_id, 2, 'KC - Managing Processes', 'kc', 10),
    (v_template_id, 2, 'KC - Managing Services', 'kc', 11),
    (v_template_id, 2, 'KC - The Bash Shell', 'kc', 12),
    (v_template_id, 2, 'KC - Bash Shell Scripts', 'kc', 13),
    (v_template_id, 2, 'KC - Software Management', 'kc', 14),
    (v_template_id, 2, 'KC - Managing Log Files', 'kc', 15),
    -- Week 2 Labs
    (v_template_id, 2, '11-[CF]-Lab - Introduction to Amazon EC2', 'lab', 1),
    (v_template_id, 2, '225-[LX]-Lab - Introduction to Amazon Linux AMI', 'lab', 2),
    (v_template_id, 2, '227-[LX]-Lab - Linux Command Line', 'lab', 3),
    (v_template_id, 2, '229-[LX]-Lab - Users and Groups', 'lab', 4),
    (v_template_id, 2, '231-[LX]-Lab - Editing Files', 'lab', 5),
    (v_template_id, 2, '233-[LX]-Lab - Working with the File System', 'lab', 6),
    (v_template_id, 2, '235-[LX]-Lab - Working with Files', 'lab', 7),
    (v_template_id, 2, '237-[LX]-Lab - Managing File Permissions', 'lab', 8),
    (v_template_id, 2, '247-[LX]-Lab - Working with Commands', 'lab', 9),
    (v_template_id, 2, '239-[LX]-Lab - Managing Processes', 'lab', 10),
    (v_template_id, 2, '241-[LX]-Lab - Managing Services and Monitoring', 'lab', 11),
    (v_template_id, 2, '243-[LX]-Lab - Software Management', 'lab', 12),
    (v_template_id, 2, '245-[LX]-Lab - Managing Log Files', 'lab', 13),
    (v_template_id, 2, '249-[LX]-Lab - The Bash Shell', 'lab', 14),
    (v_template_id, 2, '251-[LX]-Lab - Bash Shell Scripts', 'lab', 15),
    (v_template_id, 2, '253-[LX]-Lab - [Challenge] Bash Shell Scripting', 'lab', 16),
    -- Week 3 KCs
    (v_template_id, 3, 'KC - Introduction to Networking', 'kc', 1),
    (v_template_id, 3, 'KC - Networking Concepts', 'kc', 2),
    (v_template_id, 3, 'KC - Internet Protocol [IP]', 'kc', 3),
    (v_template_id, 3, 'KC - Amazon VPC', 'kc', 4),
    (v_template_id, 3, 'KC - IP Subnetting', 'kc', 5),
    (v_template_id, 3, 'KC - Additional Networking Technologies', 'kc', 6),
    (v_template_id, 3, 'KC - Additional Networking Protocols', 'kc', 7),
    -- Week 3 Labs
    (v_template_id, 3, '261-[NF]-Lab - Public and Private IP addresses', 'lab', 1),
    (v_template_id, 3, '262-[NF]-Lab - Static and Dynamic and IP addresses', 'lab', 2),
    (v_template_id, 3, '263-[NF]-Lab - Create Subnets in a VPC', 'lab', 3),
    (v_template_id, 3, '264-[NF]-Lab - Networking resources for a VPC', 'lab', 4),
    (v_template_id, 3, '265-[NF]-Lab - Internet Protocol Troubleshooting Commands', 'lab', 5),
    (v_template_id, 3, '266-[NF]-Lab - Troubleshooting a Network Issue', 'lab', 6),
    (v_template_id, 3, '267-[NF]-Lab - Build your VPC and Launch a Web Server', 'lab', 7),
    -- Week 4 KCs
    (v_template_id, 4, 'KC - Introduction to Security', 'kc', 1),
    (v_template_id, 4, 'KC - Security Lifecycle: Prevention', 'kc', 2),
    (v_template_id, 4, 'KC - Network Hardening', 'kc', 3),
    (v_template_id, 4, 'KC - Systems Hardening', 'kc', 4),
    (v_template_id, 4, 'KC - Data Security', 'kc', 5),
    (v_template_id, 4, 'KC - Public Key Infrastructure', 'kc', 6),
    (v_template_id, 4, 'KC - AWS Security Compliance Program', 'kc', 7),
    (v_template_id, 4, 'KC - Identity Management', 'kc', 8),
    (v_template_id, 4, 'KC - AWS IAM', 'kc', 9),
    (v_template_id, 4, 'KC - Detection', 'kc', 10),
    (v_template_id, 4, 'KC - AWS CloudTrail', 'kc', 11),
    (v_template_id, 4, 'KC - AWS Config', 'kc', 12),
    (v_template_id, 4, 'KC - Response', 'kc', 13),
    -- Week 4 Labs
    (v_template_id, 4, '276-[SF]-Lab - Network-Hardening', 'lab', 1),
    (v_template_id, 4, '277-[SF]-Lab - Systems-Hardening', 'lab', 2),
    (v_template_id, 4, '278-[SF]-Lab - Data Protection', 'lab', 3),
    (v_template_id, 4, '279-[SF]-Lab - Introduction to Identity and Access Management (IAM)', 'lab', 4),
    (v_template_id, 4, '280-[SF]-Lab - Firewall Malware', 'lab', 5),
    (v_template_id, 4, '281-[SF]-Lab - Monitor an EC2 Instance', 'lab', 6),
    -- Week 5 KCs
    (v_template_id, 5, 'KC - Analysis', 'kc', 1),
    (v_template_id, 5, 'KC - Trusted Advisor', 'kc', 2),
    (v_template_id, 5, 'KC - Security Best Practices', 'kc', 3),
    (v_template_id, 5, 'KC - AWS Security Resources', 'kc', 4),
    (v_template_id, 5, 'KC - Introduction to Programming', 'kc', 5),
    (v_template_id, 5, 'KC - Introduction to Python', 'kc', 6),
    (v_template_id, 5, 'KC - Python Basics', 'kc', 7),
    (v_template_id, 5, 'KC - Flow Control', 'kc', 8),
    (v_template_id, 5, 'KC - Functions', 'kc', 9),
    (v_template_id, 5, 'KC - Modules and Libraries', 'kc', 10),
    (v_template_id, 5, 'KC - Python for System Administration', 'kc', 11),
    (v_template_id, 5, 'KC - Debugging and Testing', 'kc', 12),
    (v_template_id, 5, 'KC - DevOps and Continuous Integration', 'kc', 13),
    (v_template_id, 5, 'KC - Configuration Management', 'kc', 14),
    -- Week 5 Labs
    (v_template_id, 5, '134-[PF]-Lab - Evaluate a DevOps Tool', 'lab', 1),
    (v_template_id, 5, '135-[PF]-Lab - Explore the Value of Automation', 'lab', 2),
    (v_template_id, 5, '136-[PF]-Lab - Compare and Contrast Automation and Orchestration', 'lab', 3),
    (v_template_id, 5, '141-[PF]-Lab - [Challenge] Python Exercise', 'lab', 4),
    -- Week 6 KCs
    (v_template_id, 6, 'KC - Introduction to Databases', 'kc', 1),
    (v_template_id, 6, 'KC - Creating Tables and Learning Different Data Types', 'kc', 2),
    (v_template_id, 6, 'KC - Data Interaction and Database Transaction', 'kc', 3),
    (v_template_id, 6, 'KC - Inserting Data into a Database', 'kc', 4),
    (v_template_id, 6, 'KC - Selecting Data from a Database', 'kc', 5),
    (v_template_id, 6, 'KC - Performing a Conditional Search', 'kc', 6),
    (v_template_id, 6, 'KC - Working with Functions', 'kc', 7),
    (v_template_id, 6, 'KC - Organizing Data', 'kc', 8),
    (v_template_id, 6, 'KC - Retrieving Data from Multiple Tables', 'kc', 9),
    (v_template_id, 6, 'KC - Amazon RDS', 'kc', 10),
    (v_template_id, 6, 'KC - Amazon DynamoDB', 'kc', 11),
    -- Week 6 Labs
    (v_template_id, 6, '268-[DF]-Lab - Database Table Operations', 'lab', 1),
    (v_template_id, 6, '269-[DF]-Lab - Insert, Update, and Delete Data in a Database', 'lab', 2),
    (v_template_id, 6, '270-[DF]-Lab - Selecting Data from a Database', 'lab', 3),
    (v_template_id, 6, '271-[DF]-Lab - Performing a Conditional Search', 'lab', 4),
    (v_template_id, 6, '272-[DF]-Lab - Working with Functions', 'lab', 5),
    (v_template_id, 6, '273-[DF]-Lab - Organizing Data', 'lab', 6),
    (v_template_id, 6, '274-[DF]-Lab - Introduction to Amazon Aurora', 'lab', 7),
    (v_template_id, 6, '275-[DF]-Lab - Introduction to Amazon DynamoDB', 'lab', 8),
    (v_template_id, 6, '162-[DF]-Lab - [Challenge] Build and Access an RDS Server', 'lab', 9),
    (v_template_id, 6, '160-[DF]-Lab - Build Your Database Server and Interact with Your DB Using an App', 'lab', 10),
    (v_template_id, 6, 'Activity - Introduction to Databases', 'lab', 11),
    (v_template_id, 6, 'Databases Advanced Topics', 'lab', 12),
    (v_template_id, 6, 'Activity - Creating Tables and Data Types', 'lab', 13),
    -- Week 7 KCs
    (v_template_id, 7, 'KC – AWS Architecture', 'kc', 1),
    (v_template_id, 7, 'KC - Tooling and Automation', 'kc', 2),
    (v_template_id, 7, 'KC - System Operations', 'kc', 3),
    (v_template_id, 7, 'KC - Scaling and Name Resolution', 'kc', 4),
    (v_template_id, 7, 'KC - Serverless and Containers', 'kc', 5),
    (v_template_id, 7, 'KC - Servers', 'kc', 6),
    -- Week 7 Labs
    (v_template_id, 7, '168-[JAWS]-Activity - Install and Configure the AWS CLI', 'lab', 1),
    (v_template_id, 7, '169-[JAWS]-Lab - Using AWS Systems Manager', 'lab', 2),
    (v_template_id, 7, '170-[JAWS]-Activity - Create a Website on S3', 'lab', 3),
    (v_template_id, 7, '171-[JAWS]-Lab - Creating Amazon EC2 Instances', 'lab', 4),
    (v_template_id, 7, '172-[JAWS]-Lab - [Challenge] EC2 Instance Exercise', 'lab', 5),
    (v_template_id, 7, '173-[JAWS]-Activity: Troubleshoot Create Instance', 'lab', 6),
    (v_template_id, 7, '174-[JAWS]-Lab - Scale and Load Balance your Architecture', 'lab', 7),
    (v_template_id, 7, '175-[JAWS]-Lab - Using Auto Scaling in AWS (Linux)', 'lab', 8),
    (v_template_id, 7, '176-[JAWS]-Activity - Route 53 Failover Routing', 'lab', 9),
    (v_template_id, 7, '178-[JAWS]-Activity - Working with AWS Lambda', 'lab', 10),
    (v_template_id, 7, '177-[JAWS]-Lab - [Challenge] AWS Lambda Exercise', 'lab', 11),
    -- Week 8 KCs
    (v_template_id, 8, 'KC - AWS Database Services', 'kc', 1),
    (v_template_id, 8, 'KC - AWS Networking Services', 'kc', 2),
    (v_template_id, 8, 'KC - Storage and Archiving', 'kc', 3),
    (v_template_id, 8, 'KC - Monitoring and Security', 'kc', 4),
    (v_template_id, 8, 'KC - Managing Resource Consumption', 'kc', 5),
    (v_template_id, 8, 'KC - Creating Automated Repeatable Deployments', 'kc', 6),
    -- Week 8 Labs
    (v_template_id, 8, '179-[JAWS]-Activity - Migrate to Amazon RDS', 'lab', 1),
    (v_template_id, 8, '180-[JAWS]-Lab - Configuring an Amazon VPC', 'lab', 2),
    (v_template_id, 8, '181-[JAWS]-Activity - Troubleshoot a VPC', 'lab', 3),
    (v_template_id, 8, '182-[JAWS]-Lab - Working with Amazon EBS', 'lab', 4),
    (v_template_id, 8, '183-[JAWS]-Lab - Managing Storage', 'lab', 5),
    (v_template_id, 8, '185-[JAWS]-Activity - Work with Amazon S3', 'lab', 6),
    (v_template_id, 8, '184-[JAWS]-Lab - [Challenge] S3 Exercise', 'lab', 7),
    (v_template_id, 8, '186-[JAWS]-Lab - Monitoring Infrastructure', 'lab', 8),
    (v_template_id, 8, '187-[JAWS]-Activity - Working with AWS CloudTrail', 'lab', 9),
    (v_template_id, 8, '188-[JAWS]-Lab - Managing Resources with Tagging', 'lab', 10),
    (v_template_id, 8, '189-[JAWS]-Activity - Optimize Utilization', 'lab', 11),
    (v_template_id, 8, '190-[JAWS]-Lab - Automating Deployments with AWS CloudFormation', 'lab', 12),
    (v_template_id, 8, '191-[JAWS]-Activity - Troubleshooting AWS CloudFormation Deployments', 'lab', 13),
    (v_template_id, 8, '192-[JAWS]-Lab - [Challenge] CloudFormation', 'lab', 14),
    -- Week 9 KCs (cert prep — no labs)
    (v_template_id, 9, 'KC - Scenario Test Strategy Practice', 'kc', 1),
    (v_template_id, 9, 'KC - Cloud Computing', 'kc', 2),
    (v_template_id, 9, 'KC - Cloud Economics', 'kc', 3),
    (v_template_id, 9, 'KC - AWS Global Infrastructure', 'kc', 4),
    (v_template_id, 9, 'KC - Compute', 'kc', 5),
    (v_template_id, 9, 'KC - Identity and Access Management [IAM]', 'kc', 6),
    (v_template_id, 9, 'KC - Amazon Virtual Private Cloud [VPC]', 'kc', 7),
    (v_template_id, 9, 'KC - Storage', 'kc', 8),
    (v_template_id, 9, 'KC - Databases', 'kc', 9),
    (v_template_id, 9, 'KC - Billing and Support', 'kc', 10),
    (v_template_id, 9, 'KC - Cloud Architecting', 'kc', 11),
    (v_template_id, 9, 'KC - Balancing - Scaling - Monitoring', 'kc', 12);
end;
$$;
