-- Add cohort_subtype discriminator to curriculum_templates
-- Used to distinguish University vs External practitioner variants
ALTER TABLE curriculum_templates
  ADD COLUMN IF NOT EXISTS cohort_subtype text;

-- Seed two Practitioner templates (University and External).
-- Both have the same 167 tasks extracted from the AWS re/Start Excel gradebooks.
WITH templates AS (
  INSERT INTO curriculum_templates (name, level, platform, is_default, cohort_subtype)
  VALUES
    ('AWS re/Start — Practitioner (University)', 'practitioner', 'canvas', true, 'university'),
    ('AWS re/Start — Practitioner (External)',   'practitioner', 'canvas', true, 'external')
  RETURNING id, cohort_subtype
),
task_rows (week_number, task_name, task_type, display_order) AS (
  VALUES
    -- Week 1
    (1, '1-[CF]-Lab - Sandbox Environment',                                             'lab'::task_type,  1),
    (1, 'KC - Introduction to Cloud Computing',                                          'kc',              2),
    (1, 'KC - Basic Computing Concepts',                                                 'kc',              3),
    (1, 'KC - Development Team Roles',                                                   'kc',              4),
    (1, 'KC - What is Cloud Computing?',                                                 'kc',              5),
    (1, 'KC - Advantages of Cloud Computing',                                            'kc',              6),
    (1, 'KC - What is Amazon Web Services?',                                             'kc',              7),
    (1, 'KC - Fundamentals of AWS Pricing',                                              'kc',              8),
    (1, 'KC - AWS Infrastructure Overview',                                              'kc',              9),
    (1, 'KC - AWS Services and Service Categories',                                      'kc',             10),
    (1, 'KC - Shared Responsibility Model',                                              'kc',             11),
    (1, 'KC - Introduction to Amazon S3',                                               'kc',             12),
    -- Week 2
    (2, '11-[CF]-Lab - Introduction to Amazon EC2',                                     'lab',             1),
    (2, '225-[LX]-Lab - Introduction to Amazon Linux AMI',                              'lab',             2),
    (2, '227-[LX]-Lab - Linux Command Line',                                            'lab',             3),
    (2, '229-[LX]-Lab - Users and Groups',                                              'lab',             4),
    (2, '231-[LX]-Lab - Editing Files',                                                 'lab',             5),
    (2, '233-[LX]-Lab - Working with the File System',                                  'lab',             6),
    (2, '235-[LX]-Lab - Working with Files',                                            'lab',             7),
    (2, '237-[LX]-Lab - Managing File Permissions',                                     'lab',             8),
    (2, '247-[LX]-Lab - Working with Commands',                                         'lab',             9),
    (2, '239-[LX]-Lab - Managing Processes',                                            'lab',            10),
    (2, '241-[LX]-Lab - Managing Services and Monitoring',                              'lab',            11),
    (2, '243-[LX]-Lab - Software Management',                                           'lab',            12),
    (2, '245-[LX]-Lab - Managing Log Files',                                            'lab',            13),
    (2, '249-[LX]-Lab - The Bash Shell',                                                'lab',            14),
    (2, '251-[LX]-Lab - Bash Shell Scripts',                                            'lab',            15),
    (2, '253-[LX]-Lab - [Challenge] Bash Shell Scripting',                              'lab',            16),
    (2, 'KC - Introduction to Amazon EC2',                                              'kc',             17),
    (2, 'KC - An Introduction to Linux',                                                'kc',             18),
    (2, 'KC - Linux Command Line',                                                      'kc',             19),
    (2, 'KC - Users and Groups',                                                        'kc',             20),
    (2, 'KC - Editing Files',                                                           'kc',             21),
    (2, 'KC - Working with the File System',                                            'kc',             22),
    (2, 'KC - Working with Files',                                                      'kc',             23),
    (2, 'KC - Managing File Permissions',                                               'kc',             24),
    (2, 'KC - Working with Commands',                                                   'kc',             25),
    (2, 'KC - Managing Processes',                                                      'kc',             26),
    (2, 'KC - Managing Services',                                                       'kc',             27),
    (2, 'KC - The Bash Shell',                                                          'kc',             28),
    (2, 'KC - Bash Shell Scripts',                                                      'kc',             29),
    (2, 'KC - Software Management',                                                     'kc',             30),
    (2, 'KC - Managing Log Files',                                                      'kc',             31),
    -- Week 3
    (3, '261-[NF]-Lab - Public and Private IP addresses',                               'lab',             1),
    (3, '262-[NF]-Lab - Static and Dynamic and IP addresses',                           'lab',             2),
    (3, '263-[NF]-Lab - Create Subnets in a VPC',                                       'lab',             3),
    (3, '264-[NF]-Lab - Networking resources for a VPC',                                'lab',             4),
    (3, '265-[NF]-Lab - Internet Protocol Troubleshooting Commands',                    'lab',             5),
    (3, '266-[NF]-Lab - Troubleshooting a Network Issue',                               'lab',             6),
    (3, '267-[NF]-Lab - Build your VPC and Launch a Web Server',                        'lab',             7),
    (3, 'KC - Introduction to Networking',                                              'kc',              8),
    (3, 'KC - Networking Concepts',                                                     'kc',              9),
    (3, 'KC - Internet Protocol [IP]',                                                  'kc',             10),
    (3, 'KC - Amazon VPC',                                                              'kc',             11),
    (3, 'KC - IP Subnetting',                                                           'kc',             12),
    (3, 'KC - Additional Networking Technologies',                                      'kc',             13),
    (3, 'KC - Additional Networking Protocols',                                         'kc',             14),
    -- Week 4
    (4, '276-[SF]-Lab - Network-Hardening',                                             'lab',             1),
    (4, '277-[SF]-Lab - Systems-Hardening',                                             'lab',             2),
    (4, '278-[SF]-Lab - Data Protection',                                               'lab',             3),
    (4, '279-[SF]-Lab - Introduction to Identity and Access Management(IAM)',           'lab',             4),
    (4, '280-[SF]-Lab - Firewall Malware',                                              'lab',             5),
    (4, '281-[SF]-Lab - Monitor an EC2 Instance',                                       'lab',             6),
    (4, 'KC - Introduction to Security',                                                'kc',              7),
    (4, 'KC - Security Lifecycle: Prevention',                                          'kc',              8),
    (4, 'KC - Network Hardening',                                                       'kc',              9),
    (4, 'KC - Systems Hardening',                                                       'kc',             10),
    (4, 'KC - Data Security',                                                           'kc',             11),
    (4, 'KC - Public Key Infrastructure',                                               'kc',             12),
    (4, 'KC - AWS Security Compliance Program',                                         'kc',             13),
    (4, 'KC - Identity Management',                                                     'kc',             14),
    (4, 'KC - AWS IAM',                                                                 'kc',             15),
    (4, 'KC - Detection',                                                               'kc',             16),
    (4, 'KC - AWS CloudTrail',                                                          'kc',             17),
    (4, 'KC - AWS Config',                                                              'kc',             18),
    (4, 'KC - Response',                                                                'kc',             19),
    -- Week 5
    (5, '134-[PF]-Lab - Evaluate a DevOps Tool',                                        'lab',             1),
    (5, '135-[PF]-Lab - Explore the Value of Automation',                               'lab',             2),
    (5, '136-[PF]-Lab - Compare and Contrast Automation and Orchestration',             'lab',             3),
    (5, '141-[PF]-Lab - [Challenge] Python Exercise',                                   'lab',             4),
    (5, 'KC - Analysis',                                                                'kc',              5),
    (5, 'KC - Trusted Advisor',                                                         'kc',              6),
    (5, 'KC - Security Best Practices',                                                 'kc',              7),
    (5, 'KC - AWS Security Resources',                                                  'kc',              8),
    (5, 'KC - Introduction to Programming',                                             'kc',              9),
    (5, 'KC - Introduction to Python',                                                  'kc',             10),
    (5, 'KC - Python Basics',                                                           'kc',             11),
    (5, 'KC - Flow Control',                                                            'kc',             12),
    (5, 'KC - Functions',                                                               'kc',             13),
    (5, 'KC - Modules and Libraries',                                                   'kc',             14),
    (5, 'KC - Python for System Administration',                                        'kc',             15),
    (5, 'KC - Debugging and Testing',                                                   'kc',             16),
    (5, 'KC - DevOps and Continuous Integration',                                       'kc',             17),
    (5, 'KC - Configuration Management',                                                'kc',             18),
    -- Week 6
    (6, '268-[DF]-Lab - Database Table Operations',                                     'lab',             1),
    (6, '269-[DF]-Lab - Insert, Update, and Delete Data in a Database',                 'lab',             2),
    (6, '270-[DF]-Lab - Selecting Data from a Database',                                'lab',             3),
    (6, '271-[DF]-Lab - Performing a Conditional Search',                               'lab',             4),
    (6, '272-[DF]-Lab - Working with Functions',                                        'lab',             5),
    (6, '273-[DF]-Lab - Organizing Data',                                               'lab',             6),
    (6, '274-[DF]-Lab - Introduction to Amazon Aurora',                                 'lab',             7),
    (6, '275-[DF]-Lab - Introduction to Amazon DynamoDB',                               'lab',             8),
    (6, '162-[DF]-Lab - [Challenge] Build and Access an RDS Server',                    'lab',             9),
    (6, '160-[DF]-Lab - Build Your Database Server and Interact with Your DB Using an App', 'lab',        10),
    (6, 'Activity - Introduction to Databases',                                         'lab',            11),
    (6, 'Databases Advanced Topics',                                                    'lab',            12),
    (6, 'Activity - Creating Tables and Data Types',                                    'lab',            13),
    (6, 'KC - Introduction to Databases',                                               'kc',             14),
    (6, 'KC - Creating Tables and Learning Different Data Types',                       'kc',             15),
    (6, 'KC - Data Interaction and Database Transaction',                               'kc',             16),
    (6, 'KC - Inserting Data into a Database',                                          'kc',             17),
    (6, 'KC - Selecting Data from a Database',                                          'kc',             18),
    (6, 'KC - Performing a Conditional Search',                                         'kc',             19),
    (6, 'KC - Working with Functions',                                                  'kc',             20),
    (6, 'KC - Organizing Data',                                                         'kc',             21),
    (6, 'KC - Retrieving Data from Multiple Tables',                                    'kc',             22),
    (6, 'KC - Amazon RDS',                                                              'kc',             23),
    (6, 'KC - Amazon DynamoDB',                                                         'kc',             24),
    -- Week 7
    (7, '168-[JAWS]-Activity - Install and Configure the AWS CLI',                      'lab',             1),
    (7, '169-[JAWS]-Lab - Using AWS Systems Manager',                                   'lab',             2),
    (7, '170-[JAWS]-Activity - Create a Website on S3',                                 'lab',             3),
    (7, '171-[JAWS]-Lab - Creating Amazon EC2 Instances',                               'lab',             4),
    (7, '172-[JAWS]-Lab - [Challenge] EC2 Instance Exercise',                           'lab',             5),
    (7, '173-[JAWS]-Activity: Troubleshoot Create Instance',                            'lab',             6),
    (7, '174-[JAWS]-Lab - Scale and Load Balance your Architecture',                    'lab',             7),
    (7, '175-[JAWS]-Lab - Using Auto Scaling in AWS(Linux)',                            'lab',             8),
    (7, '176-[JAWS]-Activity - Route 53 Failover Routing',                             'lab',             9),
    (7, '178-[JAWS]-Activity - Working with AWS Lambda',                               'lab',            10),
    (7, '177-[JAWS]-Lab - [Challenge] AWS Lambda Exercise',                             'lab',            11),
    (7, 'KC - AWS Architecture',                                                        'kc',             12),
    (7, 'KC - Tooling and Automation',                                                  'kc',             13),
    (7, 'KC - System Operations',                                                       'kc',             14),
    (7, 'KC - Scaling and Name Resolution',                                             'kc',             15),
    (7, 'KC - Serverless and Containers',                                               'kc',             16),
    (7, 'KC - Servers',                                                                 'kc',             17),
    -- Week 8
    (8, '179-[JAWS]-Activity - Migrate to Amazon RDS',                                  'lab',             1),
    (8, '180-[JAWS]-Lab - Configuring an Amazon VPC',                                   'lab',             2),
    (8, '181-[JAWS]-Activity - Troubleshoot a VPC',                                     'lab',             3),
    (8, '182-[JAWS]-Lab - Working with Amazon EBS',                                     'lab',             4),
    (8, '183-[JAWS]-Lab - Managing Storage',                                            'lab',             5),
    (8, '185-[JAWS]-Activity - Work with Amazon S3',                                    'lab',             6),
    (8, '184-[JAWS]-Lab - [Challenge] S3 Exercise',                                     'lab',             7),
    (8, '186-[JAWS]-Lab - Monitoring Infrastructure',                                   'lab',             8),
    (8, '187-[JAWS]-Activity - Working with AWS CloudTrail',                            'lab',             9),
    (8, '188-[JAWS]-Lab - Managing Resources with Tagging',                             'lab',            10),
    (8, '189-[JAWS]-Activity - Optimize Utilization',                                   'lab',            11),
    (8, '190-[JAWS]-Lab - Automating Deployments with AWS CloudFormation',              'lab',            12),
    (8, '191-[JAWS]-Activity - Troubleshooting AWS CloudFormation Deployments',         'lab',            13),
    (8, '192-[JAWS]-Lab - [Challenge] CloudFormation',                                  'lab',            14),
    (8, 'KC - AWS Database Services',                                                   'kc',             15),
    (8, 'KC - AWS Networking Services',                                                 'kc',             16),
    (8, 'KC - Storage and Archiving',                                                   'kc',             17),
    (8, 'KC - Monitoring and Security',                                                 'kc',             18),
    (8, 'KC - Managing Resource Consumption',                                           'kc',             19),
    (8, 'KC - Creating Automated Repeatable Deployments',                               'kc',             20),
    -- Week 9
    (9, 'KC - Scenario Test Strategy Practice',                                         'kc',              1),
    (9, 'KC - Cloud Computing',                                                         'kc',              2),
    (9, 'KC - Cloud Economics',                                                         'kc',              3),
    (9, 'KC - AWS Global Infrastructure',                                               'kc',              4),
    (9, 'KC - Compute',                                                                 'kc',              5),
    (9, 'KC - Identity and Access Management [IAM]',                                    'kc',              6),
    (9, 'KC - Amazon Virtual Private Cloud [VPC]',                                      'kc',              7),
    (9, 'KC - Storage',                                                                 'kc',              8),
    (9, 'KC - Databases',                                                               'kc',              9),
    (9, 'KC - Billing and Support',                                                     'kc',             10),
    (9, 'KC - Cloud Architecting',                                                      'kc',             11),
    (9, 'KC - Balancing - Scaling - Monitoring',                                        'kc',             12)
)
INSERT INTO template_tasks (template_id, week_number, task_name, task_type, display_order)
SELECT t.id, r.week_number, r.task_name, r.task_type, r.display_order
FROM templates t, task_rows r;
